.TH "OpenSesame" 1 "17 March 2012" "1.0"
.SH NAME
opensesame \- Simple secure quick way to generate and retrieve passwords in GNOME
.SH SYNOPSIS
opensesame
.SH DESCRIPTION
OpenSesame 1.0
.PP
\fBOpenSesame\fP allows for fast creation and retrieval of passwords in GNOME
based desktop environments. Passwords are created using APG and stored using 
GNOME-keyring. 

\fBOpenSesame\fp autostarts on login. Pressing <ctrl>+k launches the interface.
Create a new password by typing a friendly searchable name and hitting 
<Space>. To retrieve passwords, launch \fBOpenSesame\fp, type the name of the
password and hit <Enter>.  

.SH VERSION
1.0

.SH BUGS
See https://github.com/binbrain/OpenSesame/issues for a list of bugs.

.SH AUTHOR
Jim Pharis <binbrain@gmail.com>
